// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJt_LNC2xZLUfhnj905dFiVRH3u8RXvR4',
    appId: '1:319730376313:web:5b69754584dc9f6ff83ea8',
    messagingSenderId: '319730376313',
    projectId: 'todo-2478f',
    authDomain: 'todo-2478f.firebaseapp.com',
    storageBucket: 'todo-2478f.appspot.com',
    measurementId: 'G-NZJHQTK22J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA0pyMObUk0KAW6jPAXDK_P5npVdl9RPY',
    appId: '1:319730376313:android:b6398adf3c5660fbf83ea8',
    messagingSenderId: '319730376313',
    projectId: 'todo-2478f',
    storageBucket: 'todo-2478f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA51_xrUqd6KNUZftOtxlf_kdnz4D7_js8',
    appId: '1:319730376313:ios:ee30dea13d90d5baf83ea8',
    messagingSenderId: '319730376313',
    projectId: 'todo-2478f',
    storageBucket: 'todo-2478f.appspot.com',
    iosClientId: '319730376313-t5ch756sa56rqpt1btd4oomk7m858sel.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA51_xrUqd6KNUZftOtxlf_kdnz4D7_js8',
    appId: '1:319730376313:ios:ee30dea13d90d5baf83ea8',
    messagingSenderId: '319730376313',
    projectId: 'todo-2478f',
    storageBucket: 'todo-2478f.appspot.com',
    iosClientId: '319730376313-t5ch756sa56rqpt1btd4oomk7m858sel.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
